# apache-chati.conf
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    Alias /static /app/REDSOCIAL_ATI-DJANGO/chati/static
    <Directory /app/REDSOCIAL_ATI-DJANGO/chati/static>
        Require all granted
    </Directory>

    # This is the change based on your directory structure
    <Directory /app/REDSOCIAL_ATI-DJANGO/mysite>
        Require all granted
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    WSGIDaemonProcess chati python-path=/app/REDSOCIAL_ATI-DJANGO  python-home=/app/env 
    WSGIProcessGroup chati
    WSGIPassAuthorization on
    # This is the change based on your directory structure
    WSGIScriptAlias / /app/REDSOCIAL_ATI-DJANGO/mysite/wsgi.py

</VirtualHost>